# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.network "private_network", ip: "10.100.100.150"

    config.vm.provision "shell", path: "scripts/install_common.sh"
    config.vm.provision "shell", path: "scripts/install_nginx.sh"
    config.vm.provision "shell", path: "scripts/install_node.sh"
    config.vm.provision "shell", path: "scripts/install_postgis.sh"

    # Configure shell for user and root
    config.vm.provision "shell", path: "scripts/configure_shell.sh", privileged: false
    config.vm.provision "shell", path: "scripts/configure_shell.sh", privileged: true

    # Local script (not included by default)
    if File.exist?("scripts/_local.sh") then
        config.vm.provision "shell", path: "scripts/_local.sh", privileged: false
    end

    # Restart nginx server (/vagrant directory should be already mounted)
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        service nginx restart
    SHELL
end
